---
abstract: 'Inter-machine advisory file locking on NFS volumes'
author:
  - 'Steffen Mueller <smueller@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-SharedNFSLock
no_index:
  directory:
    - t
    - inc
requires:
  File::Copy: 0
  File::Spec: 0
  Sys::Hostname: 0
  Time::HiRes: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=File-SharedNFSLock
  homepage: http://search.cpan.org/search?query=File%3A%3ASharedNFSLock&mode=dist
  repository: git://github.com/fangly/file-sharednfslock.git
version: 0.04
